name: Microservice Deployment

on:
  push:
    branches:
      - master
    paths:
      - '**.js'
      - '.github/workflows/deploy.yaml'
      

  # pull_request:
  #   branches:
  #     - master
    # paths:
    #   - '**.js'
    #   - '.github/workflows/deploy.yaml'

jobs:
  deploy:
    name: Build and deploy ${{ matrix.service }} microservice
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [cart, catalogue, dispatch, payment, web, shipping, user]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: NPM install
      #   run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login (use secrets)
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ matrix.service }} -f ${{ matrix.service }}/Dockerfile ${{ matrix.service }}

      - name: Docker Push
        run: |
          docker tag ${{ matrix.service }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
